# Generated by Django 5.2.7 on 2025-11-17 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del cliente', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Ingrese el apellido del cliente', max_length=100, verbose_name='Apellido')),
                ('numero_documento', models.CharField(help_text='DNI, CUIT, o número de identificación único', max_length=20, unique=True, verbose_name='Número de Documento')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente', max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa del cliente', max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='clientes_cl_apellid_894bd6_idx'), models.Index(fields=['numero_documento'], name='clientes_cl_numero__868cb7_idx')],
            },
        ),
    ]
